routes/web.php
<?php

use Monolog\Handler\FirePHPHandler;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ForgotController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ResetController;

//Profile access
Route::get('profile/{user}', [UserController::class, 'profile'])->name('user.profile');
Route::resource('articles', ArticleController::class)->except('destroy');
Route::get('bjr', function () {
    return view('test')->withTitle('Projet Laravel -> Emir');
});

Route::get('structures', function () {
    $data = [
        'number' => '5',
        ];
    return view('structures', $data);
});

Route::get('/', function () {
    return view('welcome');
});

//Registrations
Route::get('register', [RegisterController::class, 'index'])->name('register');
Route::post('register', [RegisterController::class, 'register'])->name('post.register');

//Access login
Route::get('login', [LoginController::class, 'index'])->name('login');
Route::post('login', [LoginController::class, 'login'])->name('post.login');

//Forgetting password and reseting password
Route::get('forgot', [ForgotController::class, 'index'])->name('forgot');
Route::post('forgot', [ForgotController::class, 'store'])->name('post.forgot');

Route::get('logout', [LogoutController::class, 'logout'])->name('logout');
Route::get('reset/{token}', [ResetController::class, 'index'])->name('reset');
Route::post('reset', [ResetController::class, 'reset'])->name('post.reset');

app/Models/Article.php
<?php

namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Article extends Model
{
    use HasFactory;

    public function user() {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;
use phpDocumentor\Reflection\Types\This;

class ArticleController extends Controller
{
    protected $perPage = 5;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $articles = Article::orderByDesc('id')->paginate($this->perPage);

        $data = [
            'title'=>'Les articles - '.config('app.name'),
            'description'=> 'Retrouvez tous les articles - '.config('app.name'),
            'articles'=>$articles,
        ];

        return view('articles.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)// It is more interesting to put slug and not id in url for SEO performances
    {
        //
        return 'Cest larticle qui porte l id ' . $article->id;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        return 'changer un artilde d\'une bdd';

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/articles/index.blade.php
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{{ $description ?? '' }}">

    <title>{{ $title ?? '' }}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
</head>

<body>

    @extends('layouts.main')

    @section('content')

        <div class="row">

            {{-- <div class="mt-5 mb-5 pt-5 pb-5">
                @include('includes.sidebar')
            </div> --}}

            <div class="mt-5 mb-5 pt-5 pb-5">

                {{-- début du post --}}
                @foreach ($articles as $article)
                    <div class="card mt-4">
                        <div class="card-body">
                            <h2 class="card-title"><a
                                    href="{{ route('articles.show', ['article' => $article->id]) }}">{{ $article->title }}</a>
                            </h2>
                            <p class="card-text">{{ Str::limit($article->content, 60) }}</p>
                            <span class="auhtor">Par <a href="{{ route('user.profile', ['user' => $article->user->id])}}">{{ $article->user->name }}</a></span>
                            <span class="time">{{ $article->created_at->diffForHumans() }}</span>
                        </div>
                    </div>
                @endforeach

                <div class="Pagination mt-4">
                    {{ $articles->links() }}
                </div>

            </div>
        </div>
    </body>

    </html>
@stop